package com.bhsconsultants.vonneumanns.dataimport;

import com.bhsconsultants.vonneumanns.entities.*;
import org.springframework.stereotype.Component;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Component
public class GameDbJsonMapper {

    public void mapToGame(Map data, Game game) {
        try {
            game.setTitle((String) data.get("name"));
            game.setSummary((String)data.get("deck"));
            Map imageMap = (Map)data.get("image");
            //game.setThumbImageUrl(extractFirst(data, "image", "icon_url"));
            game.setThumbImageUrl(getStringFromMap(imageMap, "icon_url"));
            game.setScreenThumbImageUrl(extractFirst(data, "images", "icon_url"));
            game.setDescription(limit((String) data.get("description"), 500));
            game.setReleaseDate(toDate(data, "original_release_date", "yyyy-MM-dd"));
            game.setDetailsUrl((String)data.get("api_detail_url"));
            //game.setLastModified(toDate(data,"last_modified_at","yyyy-MM-dd HH:mm:ss"));
            //game.setImageUrl(selectImageUrl((List<Map>) data.get("posters"), "poster", "mid"));
        } catch (Exception e) {
            throw new GameDbException("Failed to map json for game", e);
        }
    }

    private String selectImageUrl(List<Map> data, final String type, final String size) {
        if (data==null) return null;
        for (Map entry : data) {
            Map image = (Map) entry.get("image");
            if (image.get("type").equals(type) && image.get("size").equals(size)) return (String) image.get("url");
        }
        return null;
    }


    private String extractFirst(Map data, String field, String property) {
        List<Map> inner = (List<Map>)data.get(field);
        if (inner == null || inner.isEmpty()) return null;
        return (String) inner.get(0).get(property);
    }

    private Date toDate(Map data, String field, final String pattern) throws ParseException {
        try {
            String dateString = (String) data.get(field);
            if (dateString == null || dateString.isEmpty()) return null;
            return new SimpleDateFormat(pattern).parse(dateString);
        } catch (Exception e) {
            return null;
        }
    }

    /*
	{"site_detail_url": "http://www.giantbomb.com/donkey-kong/61-311/", 
	"characters": [
		{"api_detail_url": "http://api.giantbomb.com/character/1246/", 
		"site_detail_url": "http://www.giantbomb.com/pauline/94-1246/", 
		"id": 1246, "name": "Pauline"}, {"api_detail_url": 
		"http://api.giantbomb.com/character/299/", 
		"site_detail_url": "http://www.giantbomb.com/donkey-kong/94-299/", 
		"id": 299, "name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/character/177/", 
		"site_detail_url": "http://www.giantbomb.com/mario/94-177/", 
		"id": 177, "name": "Mario"}
	], 
	"videos": [
		{"name": "Giant Bomb Mailbag: El Jugador Edition", 
		"deck": "El Dodgy Kong es muy grande!", 
		"url": "vf_mailbag_021810.mp4", 
		"image": {
			"icon_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_icon.jpg", 
			"medium_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_small.jpg", 
			"tiny_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_tiny.jpg", 
			"small_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_small.jpg", 
			"thumb_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_thumb.jpg", 
			"screen_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_screen.jpg", 
			"super_url": "http://media.giantbomb.com/uploads/0/27/1275203-screen_shot_2010_02_18_at_12.26.41_pm_super.jpg"
		}, 
		"length_seconds": 512, 
		"publish_date": "2010-02-18 13:00:00", 
		"user": "Ryan", 
		"id": 2044}
	], 
	"deck": "Control Jumpman and save his girlfriend, Pauline, from the evil barrel-tossing monkey known as Donkey Kong.", 
	"image": {
		"icon_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_icon.jpg", 
		"medium_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_small.jpg", 
		"tiny_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_tiny.jpg", 
		"small_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_small.jpg", 
		"thumb_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_thumb.jpg", 
		"screen_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_screen.jpg", 
		"super_url": "http://media.giantbomb.com/uploads/7/73888/1665767-donkeykong_front_super.jpg"
		}, 
	"locations": [
		{"api_detail_url": "http://api.giantbomb.com/location/2393/", 
		"site_detail_url": "http://www.giantbomb.com/construction-site/95-2393/", 
		"id": 2393, "name": "Construction Site"}
	], 
	"themes": [], 
	"platforms": [
		{"api_detail_url": "http://api.giantbomb.com/platform/14/", 
		"site_detail_url": "http://www.giantbomb.com/commodore-64/60-14/", 
		"id": 14, 
		"name": "Commodore 64"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/94/", 
		"site_detail_url": "http://www.giantbomb.com/pc/60-94/", 
		"id": 94, 
		"name": "PC"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/16/", 
		"site_detail_url": "http://www.giantbomb.com/zx-spectrum/60-16/", 
		"id": 16, "name": "ZX Spectrum"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/87/", 
		"site_detail_url": "http://www.giantbomb.com/wii-shop/60-87/", 
		"id": 87, "name": "Wii Shop"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/11/", 
		"site_detail_url": "http://www.giantbomb.com/amstrad-cpc/60-11/", 
		"id": 11, 
		"name": "Amstrad CPC"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/70/", 
		"site_detail_url": "http://www.giantbomb.com/atari-7800/60-70/", 
		"id": 70, 
		"name": "Atari 7800"},
		{"api_detail_url": "http://api.giantbomb.com/platform/91/", 
		"site_detail_url": "http://www.giantbomb.com/famicom-disk-system/60-91/", 
		"id": 91, 
		"name": "Famicom Disk System"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/51/", 
		"site_detail_url": "http://www.giantbomb.com/intellivision/60-51/", 
		"id": 51, 
		"name": "Intellivision"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/3/", 
		"site_detail_url": "http://www.giantbomb.com/game-boy/60-3/", 
		"id": 3, 
		"name": "Game Boy"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/21/", 
		"site_detail_url": "http://www.giantbomb.com/nes/60-21/", 
		"id": 21, 
		"name": "NES"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/84/", 
		"site_detail_url": "http://www.giantbomb.com/arcade/60-84/", 
		"id": 84, 
		"name": "Arcade"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/47/", 
		"site_detail_url": "http://www.giantbomb.com/colecovision/60-47/", 
		"id": 47, 
		"name": "ColecoVision"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/4/", 
		"site_detail_url": "http://www.giantbomb.com/game-boy-advance/60-4/", 
		"id": 4, 
		"name": "Game Boy Advance"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/40/", 
		"site_detail_url": "http://www.giantbomb.com/atari-2600/60-40/", 
		"id": 40, 
		"name": "Atari 2600"}, 
		{"api_detail_url": "http://api.giantbomb.com/platform/24/",
		"site_detail_url": "http://www.giantbomb.com/atari-8-bit/60-24/",
		 "id": 24, 
		 "name": "Atari 8-bit"}, 
		 {"api_detail_url": "http://api.giantbomb.com/platform/12/", 
		 "site_detail_url": "http://www.giantbomb.com/apple-ii/60-12/", 
		 "id": 12, 
		 "name": "Apple II"}
	], 
	"expected_release_month": null, 
	"similar_games": [
		{"api_detail_url": "http://api.giantbomb.com/game/4169/", 
		"site_detail_url": "http://www.giantbomb.com/congo-bongo/61-4169/", 
		"id": 4169, 
		"name": "Congo Bongo"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/1905/", 
		"site_detail_url": "http://www.giantbomb.com/matterhorn-screamer/61-1905/", 
		"id": 1905, 
		"name": "Matterhorn Screamer"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/14094/", 
		"site_detail_url": "http://www.giantbomb.com/jumpman-jr/61-14094/", 
		"id": 14094,
		"name": "Jumpman Jr."}, 
		{"api_detail_url": "http://api.giantbomb.com/game/32776/", 
		"site_detail_url": "http://www.giantbomb.com/der-flinke-architekt/61-32776/", 
		"id": 32776, 
		"name": "Der flinke Architekt"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/19897/", 
		"site_detail_url": "http://www.giantbomb.com/beauty-and-the-beast/61-19897/", 
		"id": 19897, 
		"name": "Beauty and the Beast"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/19687/", 
		"site_detail_url": "http://www.giantbomb.com/jumpman/61-19687/", 
		"id": 19687, 
		"name": "Jumpman"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/18310/", 
		"site_detail_url": "http://www.giantbomb.com/the-california-raisins/61-18310/", 
		"id": 18310, 
		"name": "The California Raisins"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/18285/", 
		"site_detail_url": "http://www.giantbomb.com/mario-vs-donkey-kong/61-18285/", 
		"id": 18285, 
		"name": "Mario vs. Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/8373/", 
		"site_detail_url": "http://www.giantbomb.com/bagitman/61-8373/", 
		"id": 8373, 
		"name": "Bagitman"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/19148/", 
		"site_detail_url": "http://www.giantbomb.com/hard-hat-mack/61-19148/", 
		"id": 19148, 
		"name": "Hard Hat Mack"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/14419/", 
		"site_detail_url": "http://www.giantbomb.com/popeye/61-14419/", 
		"id": 14419, 
		"name": "Popeye"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/4702/", 
		"site_detail_url": "http://www.giantbomb.com/burgertime/61-4702/", 
		"id": 4702, 
		"name": "BurgerTime"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/7406/", 
		"site_detail_url": "http://www.giantbomb.com/super-mario-bros-2/61-7406/", 
		"id": 7406, 
		"name": "Super Mario Bros. 2"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/10299/", 
		"site_detail_url": "http://www.giantbomb.com/super-mario-bros-3/61-10299/", 
		"id": 10299, 
		"name": "Super Mario Bros. 3"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/7358/", 
		"site_detail_url": "http://www.giantbomb.com/super-mario-rpg-legend-of-the-seven-stars/61-7358/", 
		"id": 7358, 
		"name": "Super Mario RPG: Legend of the Seven Stars"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/7481/", 
		"site_detail_url": "http://www.giantbomb.com/paper-mario-the-thousand-year-door/61-7481/", 
		"id": 7481,
		"name": "Paper Mario: The Thousand-Year Door"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/12739/", 
		"site_detail_url": "http://www.giantbomb.com/super-paper-mario/61-12739/", 
		"id": 12739, 
		"name": "Super Paper Mario"},
		{"api_detail_url": "http://api.giantbomb.com/game/11432/", 
		"site_detail_url": "http://www.giantbomb.com/kangaroo/61-11432/", 
		"id": 11432, 
		"name": "Kangaroo"},
		{"api_detail_url": "http://api.giantbomb.com/game/10014/", 
		"site_detail_url": "http://www.giantbomb.com/pitfall/61-10014/", 
		"id": 10014, 
		"name": "Pitfall!"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/1962/", 
		"site_detail_url": "http://www.giantbomb.com/king-kong/61-1962/", 
		"id": 1962, 
		"name": "King Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/5429/", 
		"site_detail_url": "http://www.giantbomb.com/the-lost-vikings/61-5429/", 
		"id": 5429, 
		"name": "The Lost Vikings"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/14710/", 
		"site_detail_url": "http://www.giantbomb.com/wrecking-crew/61-14710/", 
		"id": 14710, 
		"name": "Wrecking Crew"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/24579/", 
		"site_detail_url": "http://www.giantbomb.com/bugs-bunny-crazy-castle-4/61-24579/",
		"id": 24579, 
		"name": "Bugs Bunny Crazy Castle 4"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/25451/", 
		"site_detail_url": "http://www.giantbomb.com/cid-the-dummy/61-25451/", 
		"id": 25451, 
		"name": "Cid the Dummy"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/25524/", 
		"site_detail_url": "http://www.giantbomb.com/lode-runner/61-25524/",
		"id": 25524,
		"name": "Lode Runner"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/22862/", 
		"site_detail_url": "http://www.giantbomb.com/mario-wario/61-22862/", 
		"id": 22862, 
		"name": "Mario & Wario"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/25744/", 
		"site_detail_url": "http://www.giantbomb.com/donkey-kong/61-25744/", 
		"id": 25744, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/14725/", 
		"site_detail_url": "http://www.giantbomb.com/willy-the-worm/61-14725/", 
		"id": 14725, 
		"name": "Willy The Worm"},
		{"api_detail_url": "http://api.giantbomb.com/game/31113/", 
		"site_detail_url": "http://www.giantbomb.com/kong/61-31113/", 
		"id": 31113, 
		"name": "Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/31399/", 
		"site_detail_url": "http://www.giantbomb.com/jacks-crazy-cong/61-31399/", 
		"id": 31399, 
		"name": "Jack's Crazy Cong"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/31433/", 
		"site_detail_url": "http://www.giantbomb.com/jacks-crazy-cong-2/61-31433/", 
		"id": 31433, 
		"name": "Jack's Crazy Cong 2"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/17528/", 
		"site_detail_url": "http://www.giantbomb.com/fast-eddie/61-17528/", 
		"id": 17528, 
		"name": "Fast Eddie"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/7028/", 
		"site_detail_url": "http://www.giantbomb.com/super-arabian/61-7028/", 
		"id": 7028, 
		"name": "Super Arabian"}, 
		{"api_detail_url": "http://api.giantbomb.com/game/34073/", 
		"site_detail_url": "http://www.giantbomb.com/the-gunstringer/61-34073/", 
		"id": 34073, 
		"name": "The Gunstringer"}
	], 
	"images": [
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493147-donkey_kong_5_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493145-donkey_kong_3_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/1/15562/493142-donkey_kong_0_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/0/608/277824-donkey_kong_10_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/0/608/277822-donkey_kong_09_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_tiny.png",
		"small_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/0/608/277821-donkey_kong_08_super.png"}, 
		{"icon_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_icon.png", 
		"medium_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_small.png", 
		"tiny_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_tiny.png", 
		"small_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_small.png", 
		"thumb_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_thumb.png", 
		"screen_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_screen.png", 
		"super_url": "http://media.giantbomb.com/uploads/0/608/277819-donkey_kong_07_super.png"}
	], 
	"id": 311, 
	"aliases": "", 
	"first_appearance_locations": [
		{"api_detail_url": "http://api.giantbomb.com/location/2393/", 
		"id": 2393, 
		"name": "Construction Site"}
	], 
	"genres": [
		{"api_detail_url": "http://api.giantbomb.com/genre/1/", 
		"site_detail_url": "http://www.giantbomb.com/games/?sort=release_date&filter_type=genre&filter_value=1", 
		"id": 1, 
		"name": "Action"}, 
		{"api_detail_url": "http://api.giantbomb.com/genre/41/", 
		"site_detail_url": "http://www.giantbomb.com/games/?sort=release_date&filter_type=genre&filter_value=41", 
		"id": 41, 
		"name": "Platformer"}
	], 
	"people": [
		{"api_detail_url": "http://api.giantbomb.com/person/51028/", 
		"role": "Music", 
		"id": 51028, 
		"name": "Hirokazu Tanaka"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/45151/", 
		"role": "", 
		"id": 45151, 
		"name": "Gunpei Yokoi"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/614/", 
		"role": "Director", 
		"id": 614, 
		"name": "Shigeru Miyamoto"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/615/", 
		"role": "", 
		"id": 615, 
		"name": "Hiroshi Yamauchi"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/18695/", 
		"role": "Audio/Sound", 
		"id": 18695, 
		"name": "Brad Fuller"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/2410/", 
		"role": "", 
		"id": 2410, 
		"name": "Tom Sloper"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/50700/", 
		"role": "", 
		"id": 50700, 
		"name": "Kai Zeh"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/50721/", 
		"role": "", 
		"id": 50721, 
		"name": "Genyo Takeda"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/58678/", 
		"role": "", 
		"id": 58678, 
		"name": "Yukio Kaneoka"}, 
		{"api_detail_url": "http://api.giantbomb.com/person/28235/", 
		"role": "Programmer", 
		"id": 28235, 
		"name": "Garry Kitchen"}
	], 
	"original_release_date": "1981-04-22 00:00:00", 
	"first_appearance_characters": [
		{"api_detail_url": "http://api.giantbomb.com/character/177/", 
		"id": 177, 
		"name": "Mario"}, 
		{"api_detail_url": "http://api.giantbomb.com/character/299/", 
		"id": 299, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/character/311/", 
		"id": 311, 
		"name": "Cranky Kong"},
		{"api_detail_url": "http://api.giantbomb.com/character/1246/", 
		"id": 1246, 
		"name": "Pauline"}
	], 
	"developers": [
		{"api_detail_url": "http://api.giantbomb.com/company/928/", 
		"site_detail_url": "http://www.giantbomb.com/nintendo-rd1/65-928/", 
		"id": 928, "name": "Nintendo R&D1"}
	], 
	"first_appearance_objects": [
		{"api_detail_url": "http://api.giantbomb.com/object/82/", 
		"id": 82, 
		"name": "Barrel"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/120/", 
		"id": 120, 
		"name": "Fireball"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/550/", 
		"id": 550, 
		"name": "Elevator"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/308/", 
		"id": 308, 
		"name": "Hammer"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/125/", 
		"id": 125, 
		"name": "Mustache"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/329/",
		"id": 329, 
		"name": "Umbrella"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/1179/", 
		"id": 1179, 
		"name": "Platform"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/3954/", 
		"id": 3954, 
		"name": "Girders"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/5307/", 
		"id": 5307, 
		"name": "Purse"}
	], 
	"expected_release_year": 1981, 
	"publishers": [
		{"api_detail_url": "http://api.giantbomb.com/company/90/", 
		"site_detail_url": "http://www.giantbomb.com/nintendo/65-90/", 
		"id": 90, 
		"name": "Nintendo"}
	], 
	"date_last_updated": "2012-05-17 22:06:19", 
	"expected_release_quarter": null, 
	"first_appearance_people": [
		{"api_detail_url": "http://api.giantbomb.com/person/45151/", 
		"id": 45151, 
		"name": "Gunpei Yokoi"}
	], 
	"description": "<h2>Overview</h2><div class=\"js-item-cage\" rel=\"image\" title=\"image\" id=\"493143\"><div class=\"wiki-img-right\"><div class=\"wiki-img-thumb\"><a href=\"http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_super.png\" title=\"The First Level\"><img id=\"493143\" src=\"http://media.giantbomb.com/uploads/1/15562/493143-donkey_kong_1_thumb.png\" alt=\"The First Level\" /></a><div class=\"item-caption\">The First Level</div></div></div></div><p>The arcade classic Donkey Kong rose out of <a href=\"http://www.giantbomb.com/nintendo/65-90/\">Nintendo</a>'s desire to crack into the United States arcade market. The company's president back in 1981, <a href=\"http://www.giantbomb.com/hiroshi-yamauchi/72-615/\">Hiroshi Yamauchi</a>, made the decision to take a Nintendo arcade release called <a href=\"http://www.giantbomb.com/radar-scope/61-20776/\">Radar Scope</a> and see if it could be easily retrofitted to play a different, and hopefully better, game. To accomplish this task, Yamauchi chose a young employee named <a href=\"http://www.giantbomb.com/shigeru-miyamoto/72-614/\">Shigeru Miyamoto</a>. The rest, as they say, is history.</p><p>Upon going to work, Miyamoto's first attempt was to make a game based on the then-popular <a href=\"http://www.giantbomb.com/popeye/94-6403/\">Popeye</a> character. That licensing deal fell through, though Nintendo would later secure the license and develop a popular <a href=\"http://www.giantbomb.com/popeye/61-14419/\">Popeye arcade game</a>. Miyamoto had to retrofit his concept and develop three characters with similar relations to Popeye, <a href=\"http://www.giantbomb.com/olive-oyl/94-7366/\">Olive Oyl</a>, and <a href=\"http://www.giantbomb.com/bluto/94-7365/\">Bluto</a>. He came up with a little man with a mustache that was quickly named <a href=\"http://www.giantbomb.com/mario/94-177/\">Jumpman</a>, who had to save his girlfriend, <a href=\"http://www.giantbomb.com/pauline/94-1246/\">Pauline</a>, from the evil gorilla named <a href=\"http://www.giantbomb.com/donkey-kong/94-299/\">Donkey Kong</a>.</p><div class=\"js-item-cage\" rel=\"image\" title=\"image\" id=\"493144\"><div class=\"wiki-img-left\"><div class=\"wiki-img-thumb\"><a href=\"http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_super.png\" title=\"The Second Level\"><img id=\"493144\" src=\"http://media.giantbomb.com/uploads/1/15562/493144-donkey_kong_2_thumb.png\" alt=\"The Second Level\" /></a><div class=\"item-caption\">The Second Level</div></div></div></div><p>The basic story of the game is that Donkey Kong is Jumpman's pet. Jumpman mistreats Donkey Kong, who snaps and kidnaps Pauline and, in a decidedly King Kong-like twist, takes her up a building under construction. Jumpman must navigate four different levels, climbing to the top to either force Donkey Kong to move on or, in the stunning final confrontation, bring the building's girders down to make the big monkey fall.</p><p>Donkey Kong was followed-up by <a href=\"http://www.giantbomb.com/donkey-kong-jr/61-19416/\">Donkey Kong Jr.</a> , which puts the player in the role of Donkey Kong's son, <a href=\"http://www.giantbomb.com/donkey-kong-jr/94-298/\">Donkey Kong Jr.</a>, who must attempt to rescue his father from the clutches of the evil Jumpman, who by then had already been renamed Mario.</p><h2>Legacy</h2><div class=\"js-item-cage\" rel=\"image\" title=\"image\" id=\"493146\"><div class=\"wiki-img-right\"><div class=\"wiki-img-thumb\"><a href=\"http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_super.png\" title=\"The Final Level\"><img id=\"493146\" src=\"http://media.giantbomb.com/uploads/1/15562/493146-donkey_kong_4_thumb.png\" alt=\"The Final Level\" /></a><div class=\"item-caption\">The Final Level</div></div></div></div><p>Donkey Kong helped to create the platformer genre, and also was one of the first to include a story. Donkey Kong changed the way people played games; no longer was it just about <a href=\"http://www.giantbomb.com/high-score/92-260/\">high scores</a>, gamers began to play the game to find out what would happen next. Donkey Kong became one of the most iconic video games of all-time and a huge part of American pop culture, gaining mentions on countless television shows, songs, and movies. Donkey Kong also essentially launched Nintendo's biggest character of all-time, <a href=\"http://www.giantbomb.com/mario/94-177/\">Mario</a>.</p><p>As a testament to the legacy of Donkey Kong, the documetary <i>King of Kong: A Fistful of Quarters</i> was released in 2007, 26 years after the game's debut. The film was about gamer Steve Wiebe and his journey to defeat Billy Mitchell's high score, which had stood for 25 years. Public awareness about the competition for this score was raised by this film, and in the years since Wiebe, Mitchell, and others have traded positions on the top spot. Read more about the documentary at the <a href=\"http://www.billyvssteve.com/\" rel=\"nofollow\">official site</a>.</p><p>In July 2009, Donkey Kong made news yet again when a 26-year-old <a href=\"http://www.giantbomb.com/easter-egg/92-2/\">easter egg</a>, which did nothing more than display the initials of Landon M. Dyer, who worked to code the title, was uncovered after Dyer mentioned that he had forgotten how to display the initials and offered $75 to whomever can find the Easter egg first. The $75 was awarded to Don Hodges after he dug through the game's code and found the way to display the initials.</p><h2>Trivia</h2><p>The name comes from a mistranslation of the Japanese, which roughly translates to \u201cStubborn Monkey\u201d . When translating for stubborn the translator(s) came up with \u201cass\u201d or \u201cdonkey,\u201d and monkey translated to \u201cKing Kong,\u201d thus Donkey Kong.</p><p>The first console port was licensed by Nintendo but not made by them. A near perfect arcade port, and pack-in, was created for the ColecoVision system. This propelled its sales over the Atari 5200 and sold 500,000 units at launch. Over a year later Coleco made a version for its rival's Atari 2600.</p>", 
	"releases": [
		{"api_detail_url": "http://api.giantbomb.com/release/103087/", 
		"id": 103087, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/58460/", 
		"id": 58460, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/58458/", 
		"id": 58458, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/72521/", 
		"id": 72521, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/82767/", 
		"id": 82767, 
		"name": "NES Classics: Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/900/", 
		"id": 900, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/899/", 
		"id": 899, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/72450/", 
		"id": 72450, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/74764/",
		"id": 74764, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/74010/", 
		"id": 74010, 
		"name": "Donkey Kong"}, 
		{"api_detail_url": "http://api.giantbomb.com/release/72520/", 
		"id": 72520, 
		"name": "Donkey Kong"}
	], 
	"franchises": [
		{"api_detail_url": "http://api.giantbomb.com/franchise/1/", 
		"site_detail_url": "http://www.giantbomb.com/mario/62-1/", 
		"id": 1, 
		"name": "Mario"},
		 {"api_detail_url": "http://api.giantbomb.com/franchise/154/", 
		 "site_detail_url": "http://www.giantbomb.com/donkey-kong/62-154/", 
		 "id": 154, 
		 "name": "Donkey Kong"}
	], 
	"api_detail_url": "http://api.giantbomb.com/game/311/", 
	"number_of_user_reviews": 4, 
	"objects": [
		{"api_detail_url": "http://api.giantbomb.com/object/5307/", 
		"site_detail_url": "http://www.giantbomb.com/purse/93-5307/", 
		"id": 5307, 
		"name": "Purse"},
		{"api_detail_url": "http://api.giantbomb.com/object/82/", 
		"site_detail_url": "http://www.giantbomb.com/barrel/93-82/", 
		"id": 82, 
		"name": "Barrel"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/125/", 
		"site_detail_url": "http://www.giantbomb.com/mustache/93-125/", 
		"id": 125, 
		"name": "Mustache"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/308/", 
		"site_detail_url": "http://www.giantbomb.com/hammer/93-308/", 
		"id": 308, 
		"name": "Hammer"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/329/", 
		"site_detail_url": "http://www.giantbomb.com/umbrella/93-329/", 
		"id": 329, 
		"name": "Umbrella"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/520/", 
		"site_detail_url": "http://www.giantbomb.com/ladder/93-520/", 
		"id": 520, 
		"name": "Ladder"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/550/", 
		"site_detail_url": "http://www.giantbomb.com/elevator/93-550/", 
		"id": 550, 
		"name": "Elevator"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/1179/", 
		"site_detail_url": "http://www.giantbomb.com/platform/93-1179/", 
		"id": 1179, 
		"name": "Platform"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/347/", 
		"site_detail_url": "http://www.giantbomb.com/oil-drum/93-347/", 
		"id": 347, 
		"name": "Oil Drum"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/120/", 
		"site_detail_url": "http://www.giantbomb.com/fireball/93-120/", 
		"id": 120, 
		"name": "Fireball"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/375/", 
		"site_detail_url": "http://www.giantbomb.com/spring/93-375/", 
		"id": 375, 
		"name": "Spring"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/2396/", 
		"site_detail_url": "http://www.giantbomb.com/conveyor-belt/93-2396/", 
		"id": 2396, 
		"name": "Conveyor Belt"}, 
		{"api_detail_url": "http://api.giantbomb.com/object/3954/", 
		"site_detail_url": "http://www.giantbomb.com/girders/93-3954/", 
		"id": 3954, 
		"name": "Girders"}
	], 
	"original_game_rating": null, 
	"date_added": "2008-04-01 01:36:11", 
	"first_appearance_concepts": [
		{"api_detail_url": "http://api.giantbomb.com/concept/325/", 
		"id": 325,
		"name": "Moving Platforms"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2925/", 
		"id": 2925, 
		"name": "Virtual Console"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/100/", 
		"id": 100, 
		"name": "Damsel In Distress"},
		{"api_detail_url": "http://api.giantbomb.com/concept/1736/", 
		"id": 1736, 
		"name": "Mummy"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1070/", 
		"id": 1070, 
		"name": "Antagonist"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3053/", 
		"id": 3053, 
		"name": "Enemy Tossing"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2050/", 
		"id": 2050, "name": "Games Titled After the Antagonist"}
	], 
	"name": "Donkey Kong", 
	"killed_characters": [], 
	"reviews": [], 
	"concepts": [
		{"api_detail_url": "http://api.giantbomb.com/concept/1070/", 
		"site_detail_url": "http://www.giantbomb.com/antagonist/92-1070/", 
		"id": 1070, 
		"name": "Antagonist"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/54/", 
		"site_detail_url": "http://www.giantbomb.com/silent-protagonist/92-54/", 
		"id": 54, 
		"name": "Silent Protagonist"},
		{"api_detail_url": "http://api.giantbomb.com/concept/3858/", 
		"site_detail_url": "http://www.giantbomb.com/happily-ever-after/92-3858/", 
		"id": 3858, 
		"name": "Happily Ever After"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/375/", 
		"site_detail_url": "http://www.giantbomb.com/collectibles/92-375/", 
		"id": 375, 
		"name": "Collectibles"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1431/", 
		"site_detail_url": "http://www.giantbomb.com/love/92-1431/", 
		"id": 1431, 
		"name": "Love"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3214/", 
		"site_detail_url": "http://www.giantbomb.com/princess/92-3214/", 
		"id": 3214, 
		"name": "Princess"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2352/", 
		"site_detail_url": "http://www.giantbomb.com/male-protagonists/92-2352/", 
		"id": 2352, "name": "Male Protagonists"}, {"api_detail_url": 
		"http://api.giantbomb.com/concept/810/", "site_detail_url": 
		"http://www.giantbomb.com/human/92-810/", 
		"id": 810, 
		"name": "Human"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/6811/", 
		"site_detail_url": "http://www.giantbomb.com/record-making-games/92-6811/", 
		"id": 6811, 
		"name": "Record Making Games"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/100/", 
		"site_detail_url": "http://www.giantbomb.com/damsel-in-distress/92-100/", 
		"id": 100, 
		"name": "Damsel In Distress"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/260/", 
		"site_detail_url": "http://www.giantbomb.com/high-score/92-260/", 
		"id": 260, 
		"name": "High Score"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/379/", 
		"site_detail_url": "http://www.giantbomb.com/jump/92-379/", 
		"id": 379, 
		"name": "Jump"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/372/", 
		"site_detail_url": "http://www.giantbomb.com/game-over/92-372/", 
		"id": 372, 
		"name": "Game Over"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/22/", 
		"site_detail_url": "http://www.giantbomb.com/cutscene/92-22/", 
		"id": 22, 
		"name": "Cutscene"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/731/", 
		"site_detail_url": "http://www.giantbomb.com/single-screen-level/92-731/", 
		"id": 731, 
		"name": "Single-Screen Level"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/988/", 
		"site_detail_url": "http://www.giantbomb.com/porting/92-988/", 
		"id": 988, 
		"name": "Porting"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/635/", 
		"site_detail_url": "http://www.giantbomb.com/continue/92-635/", 
		"id": 635, 
		"name": "Continue"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1191/", 
		"site_detail_url": "http://www.giantbomb.com/kill-screen/92-1191/", 
		"id": 1191, 
		"name": "Kill Screen"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/725/", 
		"site_detail_url": "http://www.giantbomb.com/death/92-725/", 
		"id": 725, 
		"name": "Death"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1061/", 
		"site_detail_url": "http://www.giantbomb.com/countdown-timer/92-1061/", 
		"id": 1061, 
		"name": "Countdown Timer"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1427/", 
		"site_detail_url": "http://www.giantbomb.com/2d/92-1427/", 
		"id": 1427, 
		"name": "2D"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1601/", 
		"site_detail_url": "http://www.giantbomb.com/gravity/92-1601/", 
		"id": 1601, 
		"name": "Gravity"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1384/", 
		"site_detail_url": "http://www.giantbomb.com/intermission/92-1384/", 
		"id": 1384, 
		"name": "Intermission"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1467/", 
		"site_detail_url": "http://www.giantbomb.com/never-ending-games/92-1467/", 
		"id": 1467, 
		"name": "Never Ending Games"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1864/", 
		"site_detail_url": "http://www.giantbomb.com/climbing/92-1864/", 
		"id": 1864, 
		"name": "Climbing"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1885/", 
		"site_detail_url": "http://www.giantbomb.com/kidnapping/92-1885/", 
		"id": 1885, 
		"name": "Kidnapping"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2050/", 
		"site_detail_url": "http://www.giantbomb.com/games-titled-after-the-antagonist/92-2050/", 
		"id": 2050, 
		"name": "Games Titled After the Antagonist"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2174/", 
		"site_detail_url": "http://www.giantbomb.com/boss-assistance/92-2174/", 
		"id": 2174, 
		"name": "Boss Assistance"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2212/", 
		"site_detail_url": "http://www.giantbomb.com/no-dialogue/92-2212/", 
		"id": 2212, 
		"name": "No Dialogue"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/238/", 
		"site_detail_url": "http://www.giantbomb.com/launch-titles/92-238/", 
		"id": 238, 
		"name": "Launch Titles"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2366/", 
		"site_detail_url": "http://www.giantbomb.com/monkeys/92-2366/", 
		"id": 2366, 
		"name": "Monkeys"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/325/", 
		"site_detail_url": "http://www.giantbomb.com/moving-platforms/92-325/", 
		"id": 325, 
		"name": "Moving Platforms"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/272/", 
		"site_detail_url": "http://www.giantbomb.com/parkour/92-272/", 
		"id": 272, 
		"name": "Parkour"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2584/", 
		"site_detail_url": "http://www.giantbomb.com/multiple-death-animations/92-2584/",
		"id": 2584, 
		"name": "Multiple Death Animations"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2925/", 
		"site_detail_url": "http://www.giantbomb.com/virtual-console/92-2925/", 
		"id": 2925, 
		"name": "Virtual Console"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3124/", 
		"site_detail_url": "http://www.giantbomb.com/puzzle-platformer/92-3124/", 
		"id": 3124,
		"name": "Puzzle Platformer"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3113/", 
		"site_detail_url": "http://www.giantbomb.com/gorilla/92-3113/", 
		"id": 3113, 
		"name": "Gorilla"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3053/", 
		"site_detail_url": "http://www.giantbomb.com/enemy-tossing/92-3053/", 
		"id": 3053, 
		"name": "Enemy Tossing"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3150/", 
		"site_detail_url": "http://www.giantbomb.com/air-current/92-3150/", 
		"id": 3150, 
		"name": "Air Current"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3279/", 
		"site_detail_url": "http://www.giantbomb.com/unstable-platforms/92-3279/", 
		"id": 3279, 
		"name": "Unstable Platforms"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3475/", 
		"site_detail_url": "http://www.giantbomb.com/background-boss/92-3475/", 
		"id": 3475, 
		"name": "Background Boss"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1019/", 
		"site_detail_url": "http://www.giantbomb.com/games-on-which-movies-are-based/92-1019/", 
		"id": 1019, 
		"name": "Games on Which Movies are Based"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3782/", 
		"site_detail_url": "http://www.giantbomb.com/e-reader/92-3782/", 
		"id": 3782, 
		"name": "e-Reader"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3653/", 
		"site_detail_url": "http://www.giantbomb.com/classic-nes-series/92-3653/", 
		"id": 3653, 
		"name": "Classic NES Series"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1736/", 
		"site_detail_url": "http://www.giantbomb.com/mummy/92-1736/", 
		"id": 1736, 
		"name": "Mummy"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/3884/", 
		"site_detail_url": "http://www.giantbomb.com/promotional-drink-tie-in/92-3884/", 
		"id": 3884, 
		"name": "Promotional Drink Tie-in"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/4227/", 
		"site_detail_url": "http://www.giantbomb.com/safe-spot/92-4227/", 
		"id": 4227, 
		"name": "Safe Spot"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/2510/", 
		"site_detail_url": "http://www.giantbomb.com/falling-damage/92-2510/", 
		"id": 2510, 
		"name": "Falling Damage"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/5516/", 
		"site_detail_url": "http://www.giantbomb.com/ape/92-5516/", 
		"id": 5516, 
		"name": "Ape"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/1443/", 
		"site_detail_url": "http://www.giantbomb.com/fire/92-1443/", 
		"id": 1443, 
		"name": "Fire"}, 
		{"api_detail_url": "http://api.giantbomb.com/concept/6421/", 
		"site_detail_url": "http://www.giantbomb.com/hidden-credits/92-6421/", 
		"id": 6421, 
		"name": "Hidden Credits"}
	]}
     */
    
    
    
    /*
   [{"popularity":3,
"translated":true,
"adult":false,
"language":"en",
"original_name":"[Rec]",
"name":"[Rec]",
"alternative_name":"[REC]",
"game_type":"game",
"id":8329,
"imdb_id":"tt1038988",
"url":"http://www.thegamedb.org/game/8329",
"votes":11,
"rating":7.2,
"status":"Released",
"tagline":"One Witness. One Camera",
"certification":"R",
"overview":"\"REC\" turns on a young TV reporter and her cameraman who cover the night shift at the local fire station. Receiving a call from an old lady trapped in her house,
they reach her building to hear horrifying screams -- which begin a long nightmare and a uniquely dramatic TV report.",
"keywords":["terror",
"lebende leichen",
"obsession",
"camcorder",
"firemen",
"reality tv ",
"bite",
"cinematographer",
"attempt to escape",
"virus",
"lodger",
"live-reportage",
"schwerverletzt"],
"released":"2007-08-29",
"runtime":78,
"budget":0,
"revenue":0,
"homepage":"http://www.3l-filmverleih.de/rec",
"trailer":"http://www.youtube.com/watch?v=YQUkX_XowqI",
"genres":[{"type":"genre",
"url":"http://thegamedb.org/genre/horror",
"name":"Horror",
"id":27}],
"studios":[{"url":"http://www.thegamedb.org/company/2270",
"name":"Filmax Group",
"id":2270}],
"languages_spoken":[{"code":"es",
"name":"Spanish",
"native_name":"Espa\u00f1ol"}],
"countries":[{"code":"ES",
"name":"Spain",
"url":"http://www.thegamedb.org/country/es"}],
"posters":[{"image":{"type":"poster",
"size":"original",
"height":1000,
"width":706,
"url":"http://cf1.imgobject.com/posters/3a0/4cc8df415e73d650240003a0/rec-original.jpg",
"id":"4cc8df415e73d650240003a0"}},
{"image":{"type":"poster",
"size":"mid",
"height":708,
"width":500,
"url":"http://cf1.imgobject.com/posters/3a0/4cc8df415e73d650240003a0/rec-mid.jpg",
"id":"4cc8df415e73d650240003a0"}},
{"image":{"type":"poster",
"size":"cover",
"height":262,
"width":185,
"url":"http://cf1.imgobject.com/posters/3a0/4cc8df415e73d650240003a0/rec-cover.jpg",
"id":"4cc8df415e73d650240003a0"}},
{"image":{"type":"poster",
"size":"thumb",
"height":130,
"width":92,
"url":"http://cf1.imgobject.com/posters/3a0/4cc8df415e73d650240003a0/rec-thumb.jpg",
"id":"4cc8df415e73d650240003a0"}},
{"image":{"type":"poster",
"size":"original",
"height":1000,
"width":711,
"url":"http://cf1.imgobject.com/posters/1e7/4bc92117017a3c57fe00d1e7/rec-original.jpg",
"id":"4bc92117017a3c57fe00d1e7"}},
{"image":{"type":"poster",
"size":"mid",
"height":703,
"width":500,
"url":"http://cf1.imgobject.com/posters/1e7/4bc92117017a3c57fe00d1e7/rec-mid.jpg",
"id":"4bc92117017a3c57fe00d1e7"}},
{"image":{"type":"poster",
"size":"cover",
"height":260,
"width":185,
"url":"http://cf1.imgobject.com/posters/1e7/4bc92117017a3c57fe00d1e7/rec-cover.jpg",
"id":"4bc92117017a3c57fe00d1e7"}},
{"image":{"type":"poster",
"size":"thumb",
"height":129,
"width":92,
"url":"http://cf1.imgobject.com/posters/1e7/4bc92117017a3c57fe00d1e7/rec-thumb.jpg",
"id":"4bc92117017a3c57fe00d1e7"}},
{"image":{"type":"poster",
"size":"original",
"height":1500,
"width":1000,
"url":"http://cf1.imgobject.com/posters/1ec/4bc92118017a3c57fe00d1ec/rec-original.jpg",
"id":"4bc92118017a3c57fe00d1ec"}},
{"image":{"type":"poster",
"size":"mid",
"height":750,
"width":500,
"url":"http://cf1.imgobject.com/posters/1ec/4bc92118017a3c57fe00d1ec/rec-mid.jpg",
"id":"4bc92118017a3c57fe00d1ec"}},
{"image":{"type":"poster",
"size":"cover",
"height":278,
"width":185,
"url":"http://cf1.imgobject.com/posters/1ec/4bc92118017a3c57fe00d1ec/rec-cover.jpg",
"id":"4bc92118017a3c57fe00d1ec"}},
{"image":{"type":"poster",
"size":"thumb",
"height":138,
"width":92,
"url":"http://cf1.imgobject.com/posters/1ec/4bc92118017a3c57fe00d1ec/rec-thumb.jpg",
"id":"4bc92118017a3c57fe00d1ec"}},
{"image":{"type":"poster",
"size":"original",
"height":1429,
"width":1000,
"url":"http://cf1.imgobject.com/posters/1f1/4bc92118017a3c57fe00d1f1/rec-original.jpg",
"id":"4bc92118017a3c57fe00d1f1"}},
{"image":{"type":"poster",
"size":"mid",
"height":715,
"width":500,
"url":"http://cf1.imgobject.com/posters/1f1/4bc92118017a3c57fe00d1f1/rec-mid.jpg",
"id":"4bc92118017a3c57fe00d1f1"}},
{"image":{"type":"poster",
"size":"cover",
"height":265,
"width":185,
"url":"http://cf1.imgobject.com/posters/1f1/4bc92118017a3c57fe00d1f1/rec-cover.jpg",
"id":"4bc92118017a3c57fe00d1f1"}},
{"image":{"type":"poster",
"size":"thumb",
"height":132,
"width":92,
"url":"http://cf1.imgobject.com/posters/1f1/4bc92118017a3c57fe00d1f1/rec-thumb.jpg",
"id":"4bc92118017a3c57fe00d1f1"}},
{"image":{"type":"poster",
"size":"original",
"height":1125,
"width":800,
"url":"http://cf1.imgobject.com/posters/1f6/4bc92118017a3c57fe00d1f6/rec-original.jpg",
"id":"4bc92118017a3c57fe00d1f6"}},
{"image":{"type":"poster",
"size":"mid",
"height":703,
"width":500,
"url":"http://cf1.imgobject.com/posters/1f6/4bc92118017a3c57fe00d1f6/rec-mid.jpg",
"id":"4bc92118017a3c57fe00d1f6"}},
{"image":{"type":"poster",
"size":"cover",
"height":260,
"width":185,
"url":"http://cf1.imgobject.com/posters/1f6/4bc92118017a3c57fe00d1f6/rec-cover.jpg",
"id":"4bc92118017a3c57fe00d1f6"}},
{"image":{"type":"poster",
"size":"thumb",
"height":129,
"width":92,
"url":"http://cf1.imgobject.com/posters/1f6/4bc92118017a3c57fe00d1f6/rec-thumb.jpg",
"id":"4bc92118017a3c57fe00d1f6"}}],
"backdrops":[{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/1df/4bc92117017a3c57fe00d1df/rec-original.jpg",
"id":"4bc92117017a3c57fe00d1df"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/1df/4bc92117017a3c57fe00d1df/rec-poster.jpg",
"id":"4bc92117017a3c57fe00d1df"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/1df/4bc92117017a3c57fe00d1df/rec-thumb.jpg",
"id":"4bc92117017a3c57fe00d1df"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/1d7/4bc92113017a3c57fe00d1d7/rec-original.jpg",
"id":"4bc92113017a3c57fe00d1d7"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/1d7/4bc92113017a3c57fe00d1d7/rec-poster.jpg",
"id":"4bc92113017a3c57fe00d1d7"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/1d7/4bc92113017a3c57fe00d1d7/rec-thumb.jpg",
"id":"4bc92113017a3c57fe00d1d7"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/1e3/4bc92117017a3c57fe00d1e3/rec-original.jpg",
"id":"4bc92117017a3c57fe00d1e3"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/1e3/4bc92117017a3c57fe00d1e3/rec-poster.jpg",
"id":"4bc92117017a3c57fe00d1e3"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/1e3/4bc92117017a3c57fe00d1e3/rec-thumb.jpg",
"id":"4bc92117017a3c57fe00d1e3"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/1d3/4bc92113017a3c57fe00d1d3/rec-original.jpg",
"id":"4bc92113017a3c57fe00d1d3"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/1d3/4bc92113017a3c57fe00d1d3/rec-poster.jpg",
"id":"4bc92113017a3c57fe00d1d3"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/1d3/4bc92113017a3c57fe00d1d3/rec-thumb.jpg",
"id":"4bc92113017a3c57fe00d1d3"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/1db/4bc92114017a3c57fe00d1db/rec-original.jpg",
"id":"4bc92114017a3c57fe00d1db"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/1db/4bc92114017a3c57fe00d1db/rec-poster.jpg",
"id":"4bc92114017a3c57fe00d1db"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/1db/4bc92114017a3c57fe00d1db/rec-thumb.jpg",
"id":"4bc92114017a3c57fe00d1db"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/6f4/4d0e39c25e73d637100016f4/rec-original.jpg",
"id":"4d0e39c25e73d637100016f4"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/6f4/4d0e39c25e73d637100016f4/rec-poster.jpg",
"id":"4d0e39c25e73d637100016f4"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/6f4/4d0e39c25e73d637100016f4/rec-thumb.jpg",
"id":"4d0e39c25e73d637100016f4"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/567/4d0e39dd5e73d6370a001567/rec-original.jpg",
"id":"4d0e39dd5e73d6370a001567"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/567/4d0e39dd5e73d6370a001567/rec-poster.jpg",
"id":"4d0e39dd5e73d6370a001567"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/567/4d0e39dd5e73d6370a001567/rec-thumb.jpg",
"id":"4d0e39dd5e73d6370a001567"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/58a/4d0e39fb5e73d6371c00158a/rec-original.jpg",
"id":"4d0e39fb5e73d6371c00158a"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/58a/4d0e39fb5e73d6371c00158a/rec-poster.jpg",
"id":"4d0e39fb5e73d6371c00158a"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/58a/4d0e39fb5e73d6371c00158a/rec-thumb.jpg",
"id":"4d0e39fb5e73d6371c00158a"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/5f4/4d0e3a185e73d6370e0015f4/rec-original.jpg",
"id":"4d0e3a185e73d6370e0015f4"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/5f4/4d0e3a185e73d6370e0015f4/rec-poster.jpg",
"id":"4d0e3a185e73d6370e0015f4"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/5f4/4d0e3a185e73d6370e0015f4/rec-thumb.jpg",
"id":"4d0e3a185e73d6370e0015f4"}},
{"image":{"type":"backdrop",
"size":"original",
"height":1080,
"width":1920,
"url":"http://cf1.imgobject.com/backdrops/67f/4d0e3a395e73d6371600167f/rec-original.jpg",
"id":"4d0e3a395e73d6371600167f"}},
{"image":{"type":"backdrop",
"size":"poster",
"height":439,
"width":780,
"url":"http://cf1.imgobject.com/backdrops/67f/4d0e3a395e73d6371600167f/rec-poster.jpg",
"id":"4d0e3a395e73d6371600167f"}},
{"image":{"type":"backdrop",
"size":"thumb",
"height":169,
"width":300,
"url":"http://cf1.imgobject.com/backdrops/67f/4d0e3a395e73d6371600167f/rec-thumb.jpg",
"id":"4d0e3a395e73d6371600167f"}}],
"cast":[{"name":"Manuela Velasco",
"job":"Actor",
"department":"Actors",
"character":"Angela Vidal",
"id":34793,
"order":0,
"cast_id":1,
"url":"http://www.thegamedb.org/person/34793",
"profile":"http://cf1.imgobject.com/profiles/390/4c0157fa017a3c702d001390/manuela-velasco-thumb.jpg"},
{"name":"Carlos Lasarte",
"job":"Actor",
"department":"Actors",
"character":"C\u00e9sar",
"id":54519,
"order":2,
"cast_id":3,
"url":"http://www.thegamedb.org/person/54519",
"profile":"http://cf1.imgobject.com/profiles/ba6/4d27aa297b9aa134d3001ba6/carlos-lasarte-thumb.jpg"},
{"name":"Pablo Rosso",
"job":"Actor",
"department":"Actors",
"character":"Marcos",
"id":54520,
"order":3,
"cast_id":4,
"url":"http://www.thegamedb.org/person/54520",
"profile":""},
{"name":"David Vert",
"job":"Actor",
"department":"Actors",
"character":"Alex",
"id":54521,
"order":4,
"cast_id":5,
"url":"http://www.thegamedb.org/person/54521",
"profile":"http://cf1.imgobject.com/profiles/c7e/4d27aad57b9aa134cb001c7e/david-vert-thumb.jpg"},
{"name":"Vicente Gil",
"job":"Actor",
"department":"Actors",
"character":"Polizist",
"id":54522,
"order":5,
"cast_id":6,
"url":"http://www.thegamedb.org/person/54522",
"profile":"http://cf1.imgobject.com/profiles/c86/4d27ab237b9aa134cb001c86/vicente-gil-thumb.jpg"},
{"name":"Martha Carbonell",
"job":"Actor",
"department":"Actors",
"character":"Frau Izquierdo",
"id":54523,
"order":6,
"cast_id":7,
"url":"http://www.thegamedb.org/person/54523",
"profile":"http://cf1.imgobject.com/profiles/c90/4d27ab777b9aa134cb001c90/martha-carbonell-thumb.jpg"},
{"name":"Carlos Vicente",
"job":"Actor",
"department":"Actors",
"character":"Guillem",
"id":54524,
"order":7,
"cast_id":8,
"url":"http://www.thegamedb.org/person/54524",
"profile":"http://cf1.imgobject.com/profiles/b0f/4d27abcc7b9aa134cf001b0f/carlos-vicente-thumb.jpg"},
{"name":"Ferran Terraza",
"job":"Actor",
"department":"Actors",
"character":"Manu",
"id":54532,
"order":8,
"cast_id":22,
"url":"http://www.thegamedb.org/person/54532",
"profile":"http://cf1.imgobject.com/profiles/129/4c4bfbab7b9aa1237f000129/ferran-terraza-thumb.jpg"},
{"name":"Jorge Yamam",
"job":"Actor",
"department":"Actors",
"character":"Sergio",
"id":147878,
"order":9,
"cast_id":23,
"url":"http://www.thegamedb.org/person/147878",
"profile":"http://cf1.imgobject.com/profiles/cbb/4d27ac677b9aa134dc001cbb/jorge-yamam-thumb.jpg"},
{"name":"Jaume Balaguer\u00f3",
"job":"Director",
"department":"Directing",
"character":"",
"id":54525,
"order":0,
"cast_id":9,
"url":"http://www.thegamedb.org/person/54525",
"profile":""},
{"name":"Paco Plaza",
"job":"Director",
"department":"Directing",
"character":"",
"id":54526,
"order":0,
"cast_id":10,
"url":"http://www.thegamedb.org/person/54526",
"profile":""},
{"name":"Jaume Balaguer\u00f3",
"job":"Screenplay",
"department":"Writing",
"character":"",
"id":54525,
"order":0,
"cast_id":11,
"url":"http://www.thegamedb.org/person/54525",
"profile":""},
{"name":"Paco Plaza",
"job":"Screenplay",
"department":"Writing",
"character":"",
"id":54526,
"order":0,
"cast_id":12,
"url":"http://www.thegamedb.org/person/54526",
"profile":""},
{"name":"Luis Berdejo",
"job":"Screenplay",
"department":"Writing",
"character":"",
"id":54527,
"order":0,
"cast_id":13,
"url":"http://www.thegamedb.org/person/54527",
"profile":""},
{"name":"Julio Fern\u00e1ndez",
"job":"Producer",
"department":"Production",
"character":"",
"id":17083,
"order":0,
"cast_id":14,
"url":"http://www.thegamedb.org/person/17083",
"profile":""},
{"name":"Carlos Fern\u00e1ndez",
"job":"Executive Producer",
"department":"Production",
"character":"",
"id":37950,
"order":0,
"cast_id":15,
"url":"http://www.thegamedb.org/person/37950",
"profile":""},
{"name":"Alberto Marini",
"job":"Producer",
"department":"Production",
"character":"",
"id":54528,
"order":0,
"cast_id":16,
"url":"http://www.thegamedb.org/person/54528",
"profile":""},
{"name":"Pablo Rosso",
"job":"Director of Photography",
"department":"Camera",
"character":"",
"id":54520,
"order":0,
"cast_id":17,
"url":"http://www.thegamedb.org/person/54520",
"profile":""},
{"name":"Gemma Fauria",
"job":"Set Designer",
"department":"Art",
"character":"",
"id":54529,
"order":0,
"cast_id":18,
"url":"http://www.thegamedb.org/person/54529",
"profile":""},
{"name":"David Gallart",
"job":"Editor",
"department":"Editing",
"character":"",
"id":28500,
"order":0,
"cast_id":19,
"url":"http://www.thegamedb.org/person/28500",
"profile":""},
{"name":"Xavier Mas",
"job":"Sound Designer",
"department":"Sound",
"character":"",
"id":54530,
"order":0,
"cast_id":20,
"url":"http://www.thegamedb.org/person/54530",
"profile":""},
{"name":"Gl\u00f2ria Viguer",
"job":"Costume Design",
"department":"Costume \u0026 Make-Up",
"character":"",
"id":54531,
"order":0,
"cast_id":21,
"url":"http://www.thegamedb.org/person/54531",
"profile":""}],
"version":150,
"last_modified_at":"2011-02-20 23:16:57"}]
    */

    public void mapToPlatform(Map data, Platform platform) {
        try {
            platform.setName((String) data.get("name"));
            platform.setReleaseDate((toDate(data, "release_date", "yyyy-MM-dd")));
            Map imageMap = (Map)data.get("company");
            platform.setCompany(getStringFromMap(imageMap, "name"));
            platform.setSummary((String)data.get("deck"));
            platform.setInstallBase(((Integer) data.get("install_base")));
            imageMap = (Map)data.get("image");
            platform.setImageUrl(getStringFromMap(imageMap, "icon_url"));
        } catch (Exception e) {
            throw new GameDbException("Failed to map json for platform", e);
        }
    }

    private String getStringFromMap(Map entry, String key)
    {
    	return (entry == null ? "" : (String)entry.get(key));
    }
    
    private String limit(String text, int limit) {
        if (text==null || text.length() < limit) return text;
        return text.substring(0,limit);
    }

    public void mapToGenre(Map data, Genre genre) {
        try {
            genre.setName((String) data.get("name"));
        } catch (Exception e) {
            throw new GameDbException("Failed to map json for genre", e);
        }
    }

    public void mapToPerson(Map data, Person person) {
        try {
            person.setName((String) data.get("name"));
            person.setRole((String) data.get("role"));
        } catch (Exception e) {
            throw new GameDbException("Failed to map json for role", e);
        }
    }

    /*
    [{"popularity":3,
"name":"Glenn Strange",
"known_as":[{"name":"George Glenn Strange"},
{"name":"Glen Strange"},
{"name":"Glen 'Peewee' Strange"},
{"name":"Peewee Strange"},
{"name":"'Peewee' Strange"}],
"id":30112,
"biography":"",
"known_games":4,
"birthday":"1899-08-16",
"birthplace":"Weed,
 New Mexico,
 USA",
"url":"http://www.thegamedb.org/person/30112",
"filmography":[{"name":"Bud Abbott Lou Costello Meet Frankenstein",
"id":3073,
"job":"Actor",
"department":"Actors",
"character":"The Frankenstein Monster",
"cast_id":23,
"url":"http://www.thegamedb.org/game/3073",
"poster":"http://cf1.imgobject.com/posters/4ca/4bc9185d017a3c57fe0094ca/bud-abbott-lou-costello-meet-frankenstein-cover.jpg",
"adult":false,
"release":"1948-06-15"},
{"name":"Arizona Days (1937)",
"id":22367,
"job":"Actor",
"department":"Actors",
"character":"Henchman Pete ",
"cast_id":12,
"url":"http://www.thegamedb.org/game/22367",
"poster":"",
"adult":false,
"release":"1937-01-30"},
{"name":"House of Dracula",
"id":30793,
"job":"Actor",
"department":"Actors",
"character":"The Frankenstein Monster",
"cast_id":3,
"url":"http://www.thegamedb.org/game/30793",
"poster":"http://cf1.imgobject.com/posters/7cf/4bc97660017a3c57fe0367cf/house-of-dracula-cover.jpg",
"adult":false,
"release":"1945-01-01"},
{"name":"The Fargo Kid",
"id":38704,
"job":"Actor",
"department":"Actors",
"character":"Sheriff Dave",
"cast_id":24,
"url":"http://www.thegamedb.org/game/38704",
"poster":"http://cf1.imgobject.com/posters/04e/4d74018a5e73d6021d00004e/the-fargo-kid-cover.jpg",
"adult":false,
"release":"1940-12-06"}],
"profile":[],
"version":19,
"last_modified_at":"2011-03-07 13:02:35"}]
*/

/*
    public Roles mapToRole(String roleString) {
        if (roleString.equals("Actor")) {
            return Roles.ACTS_IN;
        }
        if (roleString.equals("Director")) {
            return Roles.DIRECTED;
        }
        return null;
    }
    */
}
